{% set name = "newversion" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/newversion-{{ version }}.tar.gz
  sha256: c7ef57eb0d5a69a92bda13033c923b4f3d1b3782d08a5821ea0aecdf0c07ea3c

build:
  noarch: python
  entry_points:
    - newversion = newversion.main:main_cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - packaging >=20.0
    - typing_extensions >=4.1.0

test:
  imports:
    - newversion
  commands:
    - pip check
    - newversion --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/vemel/newversion
  summary: PEP 440 version manager
  dev_url: https://github.com/vemel/newversion
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
