{% set name = "newversion" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/newversion-{{ version }}.tar.gz
  sha256: fe02fed950b683d6057fd359f9ba6ea31276e24579da4b730a8c9f47a8b910d9

build:
  number: 0
  noarch: python
  entry_points:
    - newversion = newversion.main:main_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - poetry
    - pip
  run:
    - python >=3.6
    - packaging >=20.0
    - typing-extensions >=3.7.4

test:
  imports:
    - newversion
  commands:
    - pip check
    - newversion --help
  requires:
    - pip

about:
  home: https://github.com/vemel/newversion
  summary: PEP 440 version manager
  dev_url: https://github.com/vemel/newversion
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
